config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :admin_users
  devise_for :users
  root "groups#index"
  resources :users, only: [:edit, :update]
  resources :groups, only: [:new, :create, :update, :edit, :show] do
    resources :messages, only: [:index, :create] 
    resources :fors, only: [:create]
    resources :againsts, only: [:create]
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable
end

app/models/against.rb
class Against < ApplicationRecord
  belongs_to :group
  belongs_to :user
  #has_many :messages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/for.rb
class For < ApplicationRecord
  belongs_to :user
  belongs_to :group
  #has_many :messages
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  has_many :messages
  has_many :fors
  has_many :againsts
  validates :name, presence: true, uniqueness: true
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user
  #belongs_to :for 
  #belongs_to :against
  validates :content, presence: true, unless: :image?

  mount_uploader :image, ImageUploader

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, length: { maximum: 6 }
  has_many :group_users
  has_many :groups, through: :group_users
  has_many :messages
  has_many :fors
  has_many :againsts
  mount_uploader :image, ImageUploader
end

app/controllers/againsts_controller.rb
class AgainstsController < ApplicationController
  def create
    @against = Against.create(user_id: current_user.id, group_id: params[:group_id])
    redirect_to group_messages_path(params[:group_id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
  end
end

app/controllers/fors_controller.rb
class ForsController < ApplicationController
  def create
    @for = For.create(user_id: current_user.id, group_id: params[:group_id])
    redirect_to group_messages_path(params[:group_id])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
    @groups = Group.all
    @group = Group.where(id: '1')
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: '作成しました'
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def show
    @group = Group.find(params[:id])
    if For.exists?(group_id: @group, user_id: current_user.id) || Against.exists?(group_id: @group, user_id: current_user.id)
      redirect_to group_messages_path(@group)
    else

    end
  end

  def update
    @group = Group.find(params[:id])
    if @group.save
      redirect_to root_path, notice: '更新しました'
    else
      render :edit
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :detail)
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)   
    @groups = Group.all
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      redirect_to group_messages_path(@group)
    else
      @messages = @group.messages.includes(:user)
      render :index
    end
  end

  private 
  
  def message_params
    if For.exists?(group_id: @group, user_id: current_user.id)
      params.require(:message).permit(:content, :image).merge(user_id: current_user.id, truth: 1)
    else
      params.require(:message).permit(:content, :image).merge(user_id: current_user.id, truth: 0)
    end
  end
  
  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def edit

  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :image, :email)
  end

end

app/helpers/againsts_helper.rb
module AgainstsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fors_helper.rb
module ForsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/groups/_form.html.haml
= form_with model: group, local: true do |f|
  - if group.errors.any?
    .SettingGroupForm__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li message
  .SettingGroupForm__field
    .SettingGroupForm__leftField
      = f.label :name, "論題名", class: 'SettingGroupForm__label'
    .SettingGroupForm__rightField
      = f.text_field :name, class: 'SettingGroupForm__input', placeholder: "論題名"
    .SettingGroupForm__leftField
      = f.label :detail, "詳細", type: 'text', class: 'SettingGroupForm__label'
    .SettingGroupForm__rightField
      = f.text_area :detail, class: 'SettingGroupForm__input', placeholder: "詳細"
  .SettingGroupForm__field
    .SettingGroupForm__leftField
    .SettingGroupForm__rightField
      = f.submit "保存", class: 'SettingGroupForm__button'

app/views/groups/edit.html.haml
.SettingGroupForm
  %h1 論題編集
  = render partial: 'form', locals: { group: @group }

app/views/groups/index.html.haml
.Wrapper
  = render partial: 'messages/side', locals: { groups: @groups }
  

app/views/groups/new.html.haml
.SettingGroupForm
  %h1 論題作成
  = render partial: 'form', locals: { group: @group }

app/views/groups/show.html.haml
.DebateShow
  .DebateContents
    .DebateTitle
      = @group.name
    .DebateDetail
      .DebateDetail__title
        詳細
      .DebateDetail__content
        = @group.detail
        少年法六一条による公表禁止
        1 成人の犯罪事件に関する報道について、特別な法的規制は存在しない。これに対して、少年法は、少年審判の非公開を定めるとともに(二二条二項(1))、六一条において、「家庭裁判所の審判に付せられた少年又は少年のときに犯した罪により公訴を提起された者については、氏名、年齢、職業、住居、容ぼう等によりその者が当該事件の本人であることを推知できるような記事又は写真を新聞紙その他の出版物に掲載してはならない」と規定している。本人特定事実の公表禁止は家庭裁判所に事件が送致される前の捜査段階にも及ぶ、と理解されている。それゆえ、少年の非行事件の場合には、通常、被疑者の逮捕から家庭裁判所の審判、処分の決定、さらにその後に至るまで、氏名、顔写真などは公表されない。
        2 少年法六一条が少年の本人特定事実の公表を禁止していることについては、少年の名誉・プライバシーを保護し、否定的な社会的烙印を回避することにより、その「健全な育成」(少年法一条)を期そうとする趣旨によるものであって、少年法の福祉・教育理念が最もよく具体化した規定である、と理解されてきた(2)。
        最近は、少年法の基本理念を、国際人権法との関連において「少年の最善の利益」として(3)、あるいは少年の人間の尊厳としての成長発達権の保障として(4)捉える見解が示されている。
    .ShowButton
      = button_to group_fors_path(@group), class: "For2" do
        賛成
      = button_to group_againsts_path(@group), class: "Against2" do
        反対

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %link{:rel => 'icon', :type => 'image/x-icon', :href => '演説.jpg'}/
    %title TO-RON
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    %link{ href: 'https://fonts.googleapis.com/earlyaccess/hannari.css', rel: 'stylesheet' }      
  %body
    -#%p.notice
      -#= notice
    -#%p.alert
      -#= alert
    = yield

app/views/messages/_main.html.haml
.Main 
  .RightHeader
    .RightHeader__content
      .RightHeader__name
        - if For.exists?(user_id: current_user.id, group_id: @group)
          %p.f-marker
            ●
        - elsif Against.exists?(user_id: current_user.id, group_id: @group)
          %p.a-marker
            ●
        - else
        = @group.name
      .RightHeader__info
        .RightHeader__data
          = icon('fas', 'user')
          = For.where(group_id: @group.id).count + Against.where(group_id: @group.id).count
        .RightHeader__data__for
          = icon('fas', 'user')
          = For.where(group_id: @group.id).count
        .RightHeader__data__against
          = icon('fas', 'user')
          = Against.where(group_id: @group.id).count
        .RightHeader__ratio
          .For__ratio
            50%
          .Against__ratio
            50%
    .RightHeader__icons
      .RightHeader__icon
        = icon('fas', 'info-circle')
      .RightHeader__icon
        = link_to edit_group_path(@group) do
          = icon('fas', 'cog') 
  .MessageField
    = render 'message'
  .Footer
    = form_with model: [@group, @message], html: {class: "Form"}, local: true do |f|
      .Form__contents
        .Form__input
          = f.text_area :content, type: 'text', class: "Form__input", placeholder: 'メッセージ' 
        .Form__content
          .Form__icons
            .Form__icon
              = f.label :image do
                = icon('fas', 'file-alt')
                = f.file_field :image, class: 'Hidden'
            .Form__icon
              = icon('fas', 'bold')
            .Form__icon
              = icon('fas', 'list-ul')
            .Form__icon
              = icon('fas', 'list-ol')
          = button_tag type: 'submit', class: 'Send' do
            = icon('fas', 'paper-plane')
            
            

app/views/messages/_message.html.haml
- @messages.each do |message|  
  - @user = User.find(message.user_id)
  - if message.user_id == 5
    .MessageBox
      .MessageBox__middle
        .MessageNeutral
          - if message.content.present?
            = message.content
          = image_tag message.image.url, class: 'Message__image' if message.image.present?    
  - elsif message.truth == true
    .MessageBox 
      .MessageFors
        .MessageIcon-for
          = image_tag @user.image.url, class: "Icon-image" 
          = @user.name       
        - if message.content.present?
          .f-triangle
            .f-white  
          .MessageFor= message.content  
        = image_tag message.image.url, class: 'Message__image' if message.image.present?
  - else
    .MessageBox
      .MessageAgainsts
        - if message.content.present?
          .MessageAgainst= message.content
          .a-triangle
            .a-white
        = image_tag message.image.url, class: 'Message__image' if message.image.present?  
        .MessageIcon-against
          = image_tag @user.image.url, class: "Icon-image" 
          = @user.name    
      

app/views/messages/_side.html.haml
.Side
  .LeftHeader 
    .LeftHeader__user
      -unless current_user.admin?
        .LeftHeader__userIcon
          = image_tag current_user.image.url, class: "Icon-image" 
        %h3.LeftHeader__userName
          = current_user.name
    %ul.LeftHeader__Icons
      %li.LeftHeader__Icon
        = link_to edit_user_path(current_user) do
          = icon('fas', 'user-cog')
      - if current_user.admin?
        %li.LeftHeader__Icon
          = link_to new_group_path do
            = icon('fas', 'plus', class: 'Close__icon')  
  .Content
    .Subjects
      .Subjects__title
        論題
        .Subjects__plus
          = link_to new_group_path do
            = icon('fas', 'plus')
      .Subjects__content
        - groups.each do |group|
          - if group == @group
            .CurrentSubject
              = link_to group_path(group) do
                ◎
                = group.name
          - else
            .Subject
              = link_to group_path(group) do
                ◎
                = group.name
      
        
        

app/views/messages/index.html.haml
.Wrapper
  = render partial: 'side', locals: { groups: @groups }
  = render 'main'

app/views/users/edit.html.haml
.AccountPage
  .AccountPage__form
    .AccountPage__title
      %h3 アカウントの編集 
    = form_for(current_user) do |f|
      .FormField
        .FormField__label--normal
          = f.label :名前
        .FormField__input--normal
          = f.text_field :name, autofocus: true
      .FormField
        .FormField__label--normal
          = f.label :アイコン
        .FormField__input--normal
          = f.file_field :image, autofocus: true
      .FormField
        .FormField__label--normal
          = f.label :メールアドレス
        .FormField__input--normal
          = f.email_field :email
      .Button
        = f.submit "更新", class: 'Button1'
        .Button2
          = link_to "ログアウト", destroy_user_session_path, method: :delete
      = link_to "トップページに戻る", :back, class: 'Button3'